### PR TITLE
generate CSV data for /workspace/:id/rack/:id

### PR DESCRIPTION
**Pull request by karenetheridge**
closes github #360.

### CODE REVIEW

**Comment by sungo** [comment]
do we know for sure that Text::CSV_XS is cool for SmartOS?

**Comment by karenetheridge** [comment]
We do not know for sure just yet, but I am about to find out.

**Comment by karenetheridge** [comment]
Text::CSV_XS passes its tests on smartos under a perlbrewed 5.26.2.

**Comment by sungo** [comment]
Can you test against pkgsrc perl? That's what we run in production.

**Comment by karenetheridge** [comment]
Text::CSV_XS 1.36 has been tested on pkgsrc perl 2.26.1.

**Pull request merged**
