### PR TITLE
New drive type validators

### LINKED ISSUE #564: Want validations for SATA HDDs
While the legacy `hardware_produce_profile` table allows for us to enumerate quantities of SATA drives that are in servers, no validation exists to count the number of `SATA_HDD` `drive_type`s being reported.

### LINKED ISSUE #586: Want validation for NVMe drives
Similar to #564, we need to be able to validate NVMe drives present in a system. These are being reported with a `drive_type` of `NVME_SSD`

### LINKED ISSUE #587: Want validation for hardware RAID LUNs
We need to be able to validate the number of RAID LUNs present on a system, such as those made with Avago MegaRAID cards.

### PR DESCRIPTION
**Pull request by karenetheridge**
- renames some hardware_product_profile columns and adds more:
    - old SSD type -> SATA SSD
    - old SATA type -> SATA HDD
    - old SAS type -> SAS HDD
    - new types: SAS SSD, NVMe SSD, RAID LUN
- new validations for the new drive types
- RAID LUNs exempted from temperature and SMART status checks

closes #564
closes #586
closes #587
closes #590 (this is a replacement; see original for more background)

### CODE REVIEW

**Comment by perigrin** [comment]
This is still changing the public API for both requests and responses, there will need to be tickets for both the UI and Shell for these changes.

**Comment by karenetheridge** [comment]
I don't think the ui does anything with the hardware_product endpoints? The shell will definitely impacted by the name changes, yes.

**Comment by sungo** [comment]
Yeah, it's labelled needs-shell. Usually I wait to file tickets for the shell until the PR gets merged.

**Comment by dustinryerson** [comment]
The UI does use the hardware_product endpoint, so it will be impacted by the changes as well.

**Pull request merged**
