### PR TITLE
gracefully handle the lack of a git repository

### PR DESCRIPTION
**Pull request by karenetheridge**
On the other hand, maybe we want to make the lack of a properly-configured git repository fatal, so it's more obvious that something went wrong with the setup?

### CODE REVIEW

**Comment by sungo** [comment]
iirc, 'describe' doesn't work well / at all if you do a shallow clone

**Comment by sungo** [comment]
Our current version string is semver. Do we want the unknown one to parse as semver too but some wacky number?

**Comment by karenetheridge** [comment]
> Do we want the unknown one to parse as semver too

I lean towards 'no'.  I'm leaning more towards doing a `$c->log->fatal` there actually, since if the git repository was set up incorrectly, who knows what other parts of the deployment went wrong too?

**Comment by sungo** [comment]
@karenetheridge are you still intending to make a lack of sensible git setup a fatal failure? I'm fine with that, for now. If we don't make it fatal, I'd like the version to parse as semver, but something ridiculous like 'v0.0.0-dirty'.

**Comment by karenetheridge** [comment]
> are you still intending to make a lack of sensible git setup a fatal failure?

If it is our expectation that sensible git is part of the correct deployment process, then I'd rather we die, so it's clear early on what happened (no one looks at logs).  This might change in the future e.g. docker or whatever but it's easy to modify later.

**Pull request merged**
